### ISSUE TITLE
`edit` can change both phone and email to be exactly the same as someone else

### ISSUE THREAD

**Issue by lithops-zty** [AY2425S1-CS2103T-F12-1/tp#154]

**Comment by weiseng18** [comment]
Interestingly, this case is caught

![image](https://github.com/user-attachments/assets/2f416687-7201-4e18-85c7-30c66e16b4dd)

But this case is not

![image](https://github.com/user-attachments/assets/da81bfb4-7230-4836-94a6-2526cc058276)
