### ISSUE TITLE
[PE-D][Tester C] Large indexes give incorrect error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-1/tp#267]
![image.png](https://raw.githubusercontent.com/arjun2598/ped/main/files/eb51a974-9494-4f95-b753-0cea2cf398e7.png)

Giving a very large index to the delete command gives the above error message, which is technically incorrect since the input index 9999999999 is actually a valid non-zero unsigned integer. Could be handled similar to the smaller indexes that are accurately identified as out of bounds. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: arjun2598/ped#10

**Comment by Elinengu** [comment]
This constitutes deliberate sabotage. The textbook says,

> Problems caused by extreme user behaviors:
If the problem happens only in case of a deliberate sabotage (e.g., user entered a 30-digit telephone number), it will not be considered a bug (in our context).
