### ISSUE TITLE
[PE-D][Tester D] Invisible character allowed in fields (Name)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-1/tp#277]
**Steps to reproduce**

1. Add contact with `add n/‎  p/00000000`

2. Enter

![Screenshot 2024-11-08 at 5.07.23 PM.png](https://raw.githubusercontent.com/clarissatjx/ped/main/files/aa6e029c-e695-4b3b-85b7-e547fd7e22c7.png)

**Severity justification**
Understand that it is not a space, but an invisible character and the ug stated any character is allowed. Invisible characters, such as non-breaking spaces or zero-width spaces, can silently distort or corrupt user input. Even though the name appears correct visually, the system stores a different value containing invisible characters, which can cause inconsistencies in future data processing or retrieval. This leads to incorrect contact information being stored in the system, which is fundamentally a data corruption problem. If a user later searches for the contact or tries to update it, the system may not recognize the contact because it is not comparing the name properly due to the invisible spaces. This could lead to frustrating user experiences, as they may think the contact has disappeared or is inaccessible. Users may also mistake invisible characters with spaces itself.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: clarissatjx/ped#8

**Comment by weiseng18** [comment]
![image](https://github.com/user-attachments/assets/bcbc2505-1dca-4f92-856d-fe5ef9e36725)

I think this should be classified as not a bug (in CS2103T context)
