### ISSUE TITLE
[PE-D][Tester D] Multiple uses of '+' in UG creates confusion

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-1/tp#289]
Refer to the 2 screenshots below, adapted from UG. This was slightly confusing and conflicting as both use '+'. Could consider using something else to indicate items that can be used one or more times

![Screenshot 2024-11-08 at 5.33.16 PM.png](https://raw.githubusercontent.com/clarissatjx/ped/main/files/fe4efef8-b523-4b46-a1b0-10a79144ebab.png)

![Screenshot 2024-11-08 at 5.34.47 PM.png](https://raw.githubusercontent.com/clarissatjx/ped/main/files/4fbecb35-828c-4846-855e-6cdcefcb91c8.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: clarissatjx/ped#9

**Comment by Elinengu** [comment]
This notation would not lead to confusion.
