### ISSUE TITLE
[PE-D][Tester D] Wrong error message shown for 'edit 1 6'

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-1/tp#309]
![Screenshot 2024-11-08 at 6.40.40 PM.png](https://raw.githubusercontent.com/clarissatjx/ped/main/files/b188c7c8-70bd-4d0d-896c-236fe36e57ed.png)

**Steps to reproduce**
1. Edit a person with `edit 1 6`.
2. Hit enter.

A wrong error message is produced. The index provided is a non-zero unsigned integer (1). What is wrong with this input is the missing fields, rather than the index.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: clarissatjx/ped#15

**Comment by weiseng18** [comment]
im guessing this could be a similar issue to #202

**Comment by lithops-zty** [comment]
Fix: Put the parsed index inside the error message

**Comment by lithops-zty** [comment]
I'm reopening this issue because I have got the prof's approval to improve clarity of the error message on this problem.
